version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '4444:4444'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/fh5-htfc
      - JWT_SECRET=sick_rat_808
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
